github_username:  dkull
theme: jekyll-theme-minimal
permalink: /:title/
title: TXT tanel.liiv.
description: Converting my thoughts to txt on topics such as software engineering, cryptography (dilettante), GNU/Linux, FOSS, etc.

